export const CONNECTED = 'OBDII_CONNECTED';
export const INITIALIZATION_REQUEST = 'OBDII_INITIALIZATION_REQUEST';
export const INITIALIZATION_SUCCESS = 'OBDII_INITIALIZATION_SUCCESS';
export const SCAN_DATA_RECEIVED = 'OBDII_SCAN_DATA_RECEIVED';
export const DATA_RECEIVED = 'OBDII_DATA_RECEIVED';
export const ERROR_RECEIVED = 'OBDII_ERROR_RECEIVED';
export const DISCONNECTED = 'OBDII_DISCONNECTED';
